//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinansalCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankProsesses
    {
        public int BankProsessID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ProsessDate { get; set; }
        public string ProsessType { get; set; }
        public Nullable<decimal> Amoun { get; set; }
        public Nullable<int> BankID { get; set; }
    
        public virtual Banks Banks { get; set; }
    }
}
